server:
  port: 9000

spring:
  application:
    name: oauth2

  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2serverauth
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
        security: DEBUG

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/