
server:
  port: 8084

spring:
  application:
    name: resource-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.http: DEBUG
    tn.thinktank: DEBUG


