server:
  port: 8083

spring:
  application:
    name: multi-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db222222
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: dummy-placeholder  # sera ignoré, remplacé dynamiquement dans le code

  # Configuration spécifique pour les tenants (utilisé dynamiquement dans le code Java)


  jwt:
    auth:
      converter:
        resource-id: alibou-rest-api         # pour Keycloak
        principle-attribute: preferred_username

jwt:
  auth:
    converter:
      resource-id: alibou-rest-api
      principle-attribute: preferred_username


  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.http: DEBUG
    org.springframework.security.oauth2: DEBUG
    tn.thinktank: DEBUG